classification:
  data:
    train_dir: "data/EuroSATallBands/train.csv"
    test_dir: "data/EuroSATallBands/test.csv"
    validation_dir: "data/EuroSATallBands/validation.csv"
    root_dir: "data/EuroSATallBands"
    output_dir: "results/"
    img_size: [256, 256]

  kmeans:
    n_clusters: 9 # HerbaceousVegetation, River, Highway, Residential, Pasture, Industrial, SeaLake, Annual Crop, Permanent Crop
    batch_pixels: 2000
    random_state: 42
    n_init: 10

  features:
    n_features: 6 # Blue, Green, Red, NIR, NDVI, NDBI
    bands_order: [2, 1, 0] # For RGB visualization

  model:
    in_channels: 4                       # RGB + NDVI
    n_classes: 10                        # Les 10 classes EuroSAT
    batch_size: 32
    learning_rate: 0.001
    epochs: 20
    model_path: "results/eurosat_cnn.pth"

segmentation:
  data: 
    train_dir: "data/SpaceNet8/Louisiana-East_Training_Public"
    train_mapping: "data/SpaceNet8/Louisiana-East_Training_Public/Louisiana-East_Training_Public_label_image_mapping.csv"
    train_masks: "data/SpaceNet8/Louisiana-East_Training_Public/masks_multiclass"
    
    test_dir: "data/SpaceNet8/Louisiana-West_Test_Publics"
    test_mapping: "data/SpaceNet8/Louisiana-West_Test_Public/Louisiana-West_Test_Public_label_image_mapping.csv"
    test_masks: "data/SpaceNet8/Louisiana-West_Test_Public/masks_multiclass"
    
    # File where png msks are stored after rasterization
    mask_dir: "data/SpaceNet8/Louisiana-East_Training_Public/masks_generated"
  model:
    architecture: "unet"
    in_channels: 3
    n_classes: 5 # 0:bg, 1:build, 2:flood_build, 3:road, 4:flood_road
    batch_size: 4
    learning_rate: 0.0001